version: '3.9'

services:
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    restart: always
    networks:
      - network

  backend:
     container_name: backend
     build:
       context: ./backend
       dockerfile: Dockerfile
     volumes:
       - /home/db.sqlite3:/djsite/db.sqlite3
     ports:
       - 8000:8000
     restart: always
     networks:
       - network

networks:
  network:
